# ---- Build Stage ----
    FROM oven/bun:1.2 AS builder

    WORKDIR /app
    
    COPY . .
    
    RUN bun install
    RUN bun run build
    
    # ---- Production Stage ----
    FROM oven/bun:1.2
    
    WORKDIR /app
    
    COPY --from=builder /app ./
    
    ENV PORT 3000
    EXPOSE 3000
    
    CMD ["bun", "start"]
    