version: '3.8'

services:
  rekit-backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/rekit-backend:latest
    container_name: rekit-backend
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/root/data/calendar.db
    volumes:
      - rekit-data:/root/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/api/events"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rekit-data:
    driver: local 