# ビルドステージ
FROM --platform=linux/amd64 golang:1.23 as builder

WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o main main_lambda.go
RUN chmod +x main

# 実行ステージ
FROM --platform=linux/amd64 public.ecr.aws/lambda/go:1

WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=builder /app/main .

CMD ["main"] 