source 'https://rubygems.org'

gem 'sinatra'
gem 'puma'
gem 'rack'
gem 'rackup'

# データベース関連
gem 'pg' # PostgreSQL用アダプター
gem 'activerecord', '~> 7.1' # ActiveRecord本体 (バージョンは適宜最新に合わせても良い)
gem 'sinatra-activerecord' # Sinatra連携

# JSON関連 (APIで必要になるでしょう)
gem 'json' # 標準ライブラリですが明示しても良い

# その他のツールなど
gem 'rake'